### PR TITLE
Can‘t know what the real reason of the fingerprint bug is.

### PR DESCRIPTION
**Pull request by YAOHAO9**
We need more detailed info for the user.

### CODE REVIEW

**Comment by phillbaker** [comment]
Hi @YAOHAO9 thanks for your PR! I've recently been added as a collaborator on this repo. Would you mind rebasing and squashing this PR?

**Comment by phillbaker** [comment]
@calcazar this PR needs to be rebased and merge conflicts resolved. Would you be able to help out?

**Comment by calcazar** [comment]
@phillbaker If you give me access I'll try my best to make it happen!

**Comment by orzhtml** [comment]
这个 PR 是否能合并？

**Comment by java-james** [comment]
This would be useful to get in. Can we get this rebased otherwise I can open another PR with this rebased?

**Comment by phillbaker** [comment]
Closing in favor of #131

**Pull request closed without merging**
