### PR TITLE
Android bug on component re-renders

### PR DESCRIPTION
**Pull request by valdio**
### NullPointerException on BiometricViewModel
App crashes on android when trying to release biometric and the fingerprint modal is already off-screen.
The react component re-render already released biometric or reference to the biometricPrompt has been lost.

I suspect that the issue is triggered at this particular part of the code, `FingerprintScanner.release();` when the component dismounts in android. 

I have noticed this issue in two cases:
1. after requesting biometric identification the user directly navigates on another screen, causing the `FingerprintScanner.release();` to be called on component dismount. I am using `react-navigation` in this case.
2. after appCenter code push is installed and the app reloads on the same component again causing `FingerprintScanner.release();` to be called.

## Issues:
I had 2 separate issues reported causing NullPointerExceptions on different stages of the release process of the biometric modal, as listed bellow:

```
NullPointerException
Attempt to invoke virtual method 'androidx.biometric.CancellationSignalProvider androidx.biometric.BiometricViewModel.getCancellationSignalProvider()' on a null object reference

NullPointerException
Attempt to invoke virtual method 'androidx.biometric.BiometricPrompt$CryptoObject androidx.biometric.BiometricViewModel.getCryptoObject()' on a null object reference

```
All these crashes originate on the same Android native component, `BiometricViewModel`, related to the prompt requesting the biometric ID.

Possibly this fix also applies to this [open issue](https://github.com/hieuvp/react-native-fingerprint-scanner/issues/193
), but I have no way to test it. 

# Use case in production build: 
This is a screenshot after applying the fix and logging the error. 
Screen Shot 2022-01-11 at 15 29 54

### CODE REVIEW

**Review by mikehardy — COMMENTED** [review]
Do you have the full stack trace of those crashes, with line numbers?
The issue you connected as maybe related (#193) is a NoClassDefFound problem, that won't be the same as a NullPointerException, I think they're unrelated.

It seems really strange that in a single-threaded system (the react-native main thread across the bridge, even if async is I think still single-threaded) could take a null pointer on something that was just tested for null, so the full stack from `adb logcat` would be useful

If there really is a null pointer on the object right after testing it for null, then it seems this may be one of the rare correct uses of the `synchronized` keyword in Java, and wrapping the critical section (where biometricPrompt was tested for null, then used if non-null during release, then set to null) in a synchronized block might fix it more correctly than a "try / swallow errors" approach

What do you think?

**Comment by valdio** [comment]
I am linking below the sentry stack traces of these errors. So far I have been able to see them only in production builds.
https://sentry.io/share/issue/7c41fff8b7254655a55c0533d1276a90/
https://sentry.io/share/issue/6fc8176ea1c04b3b847f61d9bfc2a1ec/
https://sentry.io/share/issue/d9261d7e2ac942dcbce8d3f5201e7ad0/

I also agree that silencing the errors is not the best solution, I just could not find a better approach to handle on React to these cases when the biometric modal has been removed/lost. 
I will keep looking into this a bit more but feel free to jump in and have a look if you have the time. Would really appreciate it. 🙂

Regarding the NoClassDefFound problem, you are right that my solution does not fix it because it's catching the wrong exception, my bad. Still, that issue is related to the biometric modal, but please ignore it from my description.

**Comment by valdio** [comment]
@mikehardy Thanks for the suggestion. the so synchronized approach for the release method actually worked perfectly for this bug.

**Review by mikehardy — APPROVED** [review]
Fascinating - your sentry stack traces with line numbers were perfect, thanks for sharing those. Remarkable that multiple threads were apparently able to get in to release at the same time. For a full diagnosis it seems interesting (but not required...) to understand *how* that happens, as it runs a little contrary to my mental model of the JS/Native bridge functioning on react-native, but that's my problem ;-), not a problem with the fix.

Given multiple threads must be getting in there to cause those stacks, and given synchronized was made for that case and it appears to solve your problem, this seems like the clean minimal fix.

Works for me :-)

**Comment by mikehardy** [comment]
@valdio I have never done a release on this project and don't have the time to try to learn now, many apologies, but you may rely directly on the commit hash via a direct git reference  in your package.json now that it is merged to master, and that will produce stable / reliable / trace-able builds - https://github.com/hieuvp/react-native-fingerprint-scanner/commit/45da58ad1d683a70d13dd49bc4b79cd73a0e0709

**Comment by valdio** [comment]
@mikehardy I can help you with the release, or I can handle it if you give me access to the npm.js package.

**Comment by mikehardy** [comment]
Sorry, I'm not comfortable re-delegating any authority I've got here at the moment until I've at least done it once myself. That is a little obstructive (I am sorry) but I feel like any re-delegation comes with the promise that if anything at all breaks, I can fix it, and right now I can't make that statement with any confidence since I haven't done it. A commit hash is hopefully sufficient indefinitely though until I have a chance to actually run a release etc (or someone that already has authority does).

**Comment by valdio** [comment]
I understand. No problem on my side, just wanted to help. 

But using the commit hash is no problem. 

Thank you again for merging this fix.

**Pull request merged**
