### PR TITLE
added .podspec for better manual ingeration

### PR DESCRIPTION
**Pull request by egv**
As far as I can see the most popular way of integrating native code in rn apps is through using local podspecs, that's why I have made one for this lib

### CODE REVIEW

**Comment by lucasbento** [comment]
What do you mean by _better manual integration_? Isn't `react-native link` enough?!

**Comment by hhunaid** [comment]
cocoapods is kind of a standard in dependency management for iOS. Support for it should be welcome.

**Comment by phillbaker** [comment]
Coming full circle on this, looks like podspecs are the new way forward post rn 0.60.

An example fully based on the package.json file is https://github.com/react-native-community/react-native-webview/blob/master/react-native-webview.podspec

**Comment by roshangm1** [comment]
Can this PR be improved and merged ?

**Comment by phillbaker** [comment]
For now please see initial support for react-native 60 discussed here: https://github.com/hieuvp/react-native-fingerprint-scanner/issues/88#issuecomment-509029237

**Comment by phillbaker** [comment]
Also done in 7e828060e30274c6def68bf5b01dd8af28954586

**Pull request closed without merging**
