### PR TITLE
[android] pass required args to fix broken auth

### PR DESCRIPTION
**Pull request by rajaishwary**
Fixes: https://github.com/hieuvp/react-native-fingerprint-scanner/issues/116

### CODE REVIEW

**Comment by fkotsian** [comment]
Hi @rajaishwary , 

Thanks very much for this! Can you confirm that this build enabled Face Unlock for you? Apologies that I have to ask, as I do not currently have access to a Face Unlock device. 

Thanks! Look forward to merging this into the 4.0.0 release

Frank

**Comment by fkotsian** [comment]
@rajaishwary If you could also rebase your PR to master, we did some shenanigans as we realized we had pushed a rebased branch to master 😞 . 

Have tested your commit and can confirm that it works for my current device 😄

**Comment by rajaishwary** [comment]
@fkotsian Yeah i tested the face unlock. It worked for me but the priority is fingerprint.

Scenerios,
1. fingerprint, faceunlock enrolled - fingerprint prompt pops up
2. no fingerprint, faceunlock - face unlock prompt.

Just wanted to confirm that is this native behaviour or we defined in lib.

**Comment by rajaishwary** [comment]
@fkotsian rebased PR.

**Comment by fkotsian** [comment]
@rajaishwary Thanks very much! Yeah, this is indeed native behavior, Androidx biometricPrompt delegates to the "user's preferred biometric", whatever that means. This is allegedly dependent on a preferred biometric in device Settings, though fwiw I don't see that on some devices

Thanks for PR, I will merge in and release this as part of 4.0.0

https://developer.android.com/reference/androidx/biometric/BiometricPrompt.html
https://stackoverflow.com/questions/55352879/customize-biometricprompt

**Pull request merged**
