### PR TITLE
feat: return additional biometric statuses

### PR DESCRIPTION
**Pull request by java-james**
A rebased take of #44 
Includes fix from #130

### CODE REVIEW

**Comment by phillbaker** [comment]
Thanks for updating and consolidating, much appreciated. This might be a technicality, but is changing the returned error codes a "breaking change"? By merging this do we need a major version bump in the package?

**Comment by mikehardy** [comment]
I could imagine someone handling error messages in a switch, and this would change the way that worked, which is a breaking change I think. Luckily they give away major versions for free on the internet :-) so when in doubt you can do it just in case with a note to devs about the case that may have impact

**Comment by java-james** [comment]
I agree it's got breaking changes for consumers and should have a major version bump

**Comment by aiden-petersen** [comment]
Hold the PR, there are a few error cases in the isSensorAvailable function that will never be returned. Ill send update to fix that

**Comment by java-james** [comment]
Thanks @aiden-petersen

**Comment by aiden-petersen** [comment]
@java-james Have removed a few un-used error cases, PR looks good to go now.

**Pull request merged**
