### PR TITLE
feat: Face ID

### PR DESCRIPTION
**Pull request by hieuvp**
Closes #37 #36

### CODE REVIEW

**Comment by nehab05a** [comment]
Hey @hieuvp may I know when is it planned to get this stuff released? My PR on the other project completely depends on this one.

**Comment by nehab05a** [comment]
@hieuvp Any progress on this?

**Comment by sbycrosz** [comment]
Any chance for this to get merged @hieuvp ?

**Comment by rikur** [comment]
@hieuvp have a look at my fork. Works for me with my changes.

**Comment by Gringox** [comment]
Any chance this will get merged soon?

**Comment by adamTrz** [comment]
+1

**Comment by nehab05a** [comment]
+1

**Comment by thymikee** [comment]
@hieuvp anything we could do to help you with shipping this feature?

**Comment by locphan2207** [comment]
Why is this PR not merged yet?

**Comment by wfortin** [comment]
Any update on this? Is this project still maintained?

**Comment by phillbaker** [comment]
Hi all! @hieuvp has added me as a collaborator to this repo. I'm going to be working to prune and update PRs and issues over the next couple of weeks. 

My current game plan is to merge #37 and then rebase this PR so that a review of this PR is a little more manageable.

**Comment by phillbaker** [comment]
Just an update here, parts of this PR including 9301f56 with the com.wei.android.lib:fingerprintidentify bump have been merged in #56 and released in the latest version.

**Comment by phillbaker** [comment]
Closing as all but 9b258eb have been cherry-picked or superceded by other work.

**Pull request closed without merging**
